# Generated by Django 3.0.2 on 2020-01-31 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DirectAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectUploadsDir', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MobileAlbum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileUploadsDir', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mobilepics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MobileUploadsPics', models.CharField(max_length=100)),
                ('directoryLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pics.MobileAlbum')),
            ],
        ),
        migrations.CreateModel(
            name='DirectUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DirectUploadPics', models.CharField(max_length=100)),
                ('directoryLink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pics.DirectAlbum')),
            ],
        ),
    ]
