# Generated by Django 3.0.2 on 2020-01-31 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('FullName', models.CharField(max_length=300)),
                ('PermanentAddress', models.CharField(max_length=200)),
                ('MailingAddress', models.CharField(max_length=200)),
                ('DOB', models.DateField(max_length=8)),
            ],
        ),
    ]
